export const studentTraductions = {
    en: {
        action: 'Actions',
        addSeq: 'Ajouter une séquence',
        addTrim: 'Ajouter un trimestre',
        addStudent: 'Ajouter un étudiant en ',
        editStudent: 'Editer un étudiant',
        studentName: 'Nom de l\'étudiant :',
        studentSubname: 'Prénom de l\'étudiant :',
        studentClassname: 'Classe de l\'étudiant',
        fatherEmail: 'Email du parent :',
        fatherNumber: 'Numéro de téléphone du parent :',
        fatherName: 'Nom du parent :',
        fatherProfession: 'Profession du parent :',
        importStudent: 'Importer les étudiants',
        loading: 'En cours...',
        number: 'Numéro de téléphone de l\'étudiant :',
        birthday: 'Date de naissance de l\'étudiant :',
        close: 'Fermer (Annuler)',
        enterData: 'Entrer les notes',
        seeData: 'Voir les données',
        studentList: 'Liste des étudiants en ',
        downloadCsv: 'Telecharger la liste au format csv',
        downloadPdf: 'Telecharger la liste au format pdf',
        range: 'Ranger',
        name: 'Nom',
        sex: 'Sex de l\'étudiant',
        subname: 'Prenom',
        edit: 'Editer',
        class: 'Classe',
        school: 'School',
        mr: 'Matr.',
        delete: 'Supprimer',
        mat: 'Maternelle',
        specialSeq: 'Séquence type spécial',
        addAnnualExam: 'Ajouter un examen annuel',
        specialTrim: 'Trimestre type spécial',
        specialAnnualExam: 'Examen annuel type spécial',
        noSeq: 'Aucune séquence pour l\'instant.',
        examName: 'Nom de l\'examen annuel',
        noTrim: 'Aucun trimestre pour l\'instant.',
        noAnnualExam: 'Aucun examen annuel pour l\'instant.',
        fr: 'Francophone',
        en: 'Anglogphone',
        s: 'Sexe',
        deleting: 'Suppression...',
        noStudent: 'Aucun étudiant en',
        now: 'pour l\'instant.',
        doYou: 'Voulez-vous',
        add: 'ajouter ?',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        selectSex: '--- Selectionner le sexe de l\'étudiant ----',
        m: 'Masculin',
        b: 'Date de naissance',
        f: 'Féminin',
        n: 'Numéro',
        newStudent: 'Nouveau étudiant ?',
        birthday_place: 'Lieu de naissance'
    },
    fr: {
        action: 'Actions',
        addSeq: 'Ajouter une séquence',
        addTrim: 'Ajouter un trimestre',
        addStudent: 'Ajouter un étudiant en ',
        editStudent: 'Editer un étudiant',
        studentName: 'Nom de l\'étudiant :',
        studentSubname: 'Prénom de l\'étudiant :',
        studentClassname: 'Classe de l\'étudiant',
        fatherEmail: 'Email du parent :',
        fatherNumber: 'Numéro de téléphone du parent :',
        fatherName: 'Nom du parent :',
        fatherProfession: 'Profession du parent :',
        importStudent: 'Importer les étudiants',
        loading: 'En cours...',
        number: 'Numéro de téléphone de l\'étudiant :',
        birthday: 'Date de naissance de l\'étudiant :',
        close: 'Fermer (Annuler)',
        enterData: 'Entrer les notes',
        seeData: 'Voir les données',
        studentList: 'Liste des étudiants en ',
        downloadCsv: 'Telecharger la liste au format csv',
        downloadPdf: 'Telecharger la liste au format pdf',
        range: 'Ranger',
        name: 'Nom',
        sex: 'Sex de l\'étudiant',
        subname: 'Prenom',
        examName: 'Nom de l\'examen annuel',
        edit: 'Editer',
        class: 'Classe',
        school: 'School',
        mr: 'Matr.',
        delete: 'Supprimer',
        mat: 'Maternelle',
        specialSeq: 'Séquence type spécial',
        addAnnualExam: 'Ajouter un examen annuel',
        specialTrim: 'Trimestre type spécial',
        specialAnnualExam: 'Examen annuel type spécial',
        noSeq: 'Aucune séquence pour l\'instant.',
        noTrim: 'Aucun trimestre pour l\'instant.',
        noAnnualExam: 'Aucun examen annuel pour l\'instant.',
        fr: 'Francophone',
        en: 'Anglogphone',
        s: 'Sexe',
        deleting: 'Suppression...',
        noStudent: 'Aucun étudiant en',
        now: 'pour l\'instant.',
        doYou: 'Voulez-vous',
        add: 'ajouter ?',
        save: 'Enregistrer',
        saving: 'Enregistrement...',
        selectSex: '--- Selectionner le sexe de l\'étudiant ----',
        m: 'Masculin',
        b: 'Date de naissance',
        f: 'Féminin',
        n: 'Numéro',
        newStudent: 'Nouveau étudiant ?',
        birthday_place: 'Lieu de naissance'
    }
}